language: ruby
rvm:
  - 1.9.2
  - 1.9.3
script: bundle exec rspec spec
notifications:
  email: false
  campfire:
    rooms:
      - secure: "Odwby9dDRM7J7+erXdm8VUccO2D9V0478niUtGa+QYH13vvw2IiUDokO33aj\nEZpcaNEr2hDrR6OBXQdgHeZbfTY7Fw3ASlAq0V2W1qulZPsVhobWK93cFWty\niYPmGuA4x+Y8xo9Dsx0s7g9KFNabsAZZJD5PVGPotSGMDc2dtY4="
