sudo: false
language: ruby
env:
  global:
    - secure: Kkl8Hb+HYDOZDEkgzBKyfzXI9sD+ElObEOFO8m72fLg9KoXuItklOtr/OaZmZwtGfQk3RBjieVEQ3fV+Zi26um8Rx6LbTbkjXX95tR5pfIgjYNj8KCAGncmofXsjnex+zqbiElhRmKzgQ0JK/GdVNaLc7anPHptwKiMt5LDLkXE=
rvm:
- 2.3.0
script: bundle exec rake
notifications:
  email: false
  slack:
    secure: B4f/4nYxUbGzdazor4GBSgFng9fRURmtcf4/RoGkiVFuK5AvsrGpkaOWHPSKdjDH+glfqkSUQ3ilfteG04dtEZRAB7+0hT5G62tDXR5I9Oki32ZbLNH6Y3U13PeOLd2YeDm63RxbnZgLpx1X9pYiTPyqgoQVK3kcNLqvtplJu2Q=
