language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - jruby
  - rbx-2
before_install: rm -f Gemfile.lock
script: bundle exec rspec spec
notifications:
  email: false
  webhooks:
    secure: "RBjGPOWV3WxqSk9Ug+iLM1ZuVQmAob5JtE325dz7310x5uoDrVxk7ZLo3mMC62trbKRFkgovdfs81Wyu9/yFLzEezE2AaAcJzxINQPveqrJ8a+5HoAsbE2+1R2pmpeEgFRRVAx4foh3n4a+juXSaOjV+w8gZJBU6U7/4H4vQnSE="
